from app.models.daily_assignment import DailyAssignment
from app.models.daily_assignment_item import DailyAssignmentItem
from app.models.business_rule import BusinessRule
from app.models.cleaning_plan_assignment import CleaningPlanAssignment
from app.models.cleaning_plan_assignment_employee import CleaningPlanAssignmentEmployee
from app.models.cleaning_plan_assignment_road import CleaningPlanAssignmentRoad
from app.models.collection_execution_event import CollectionExecutionEvent
from app.models.collection_route import CollectionRoute
from app.models.collection_route_bin import CollectionRouteBin
from app.models.collection_route_crew_assignment import CollectionRouteCrewAssignment
from app.models.cleaning_status_event import CleaningStatusEvent
from app.models.cleaning_zone import CleaningZone
from app.models.employee import Employee
from app.models.daily_assignment_map_target import DailyAssignmentMapTarget
from app.models.map_asset import MapAsset
from app.models.municipality_boundary import MunicipalityBoundary
from app.models.platform_module import PlatformModule
from app.models.role import Role
from app.models.sector import Sector
from app.models.sector_item import SectorItem
from app.models.shift import Shift
from app.models.road_segment import RoadSegment
from app.models.user import AppUser
from app.models.user_role import UserRole
from app.models.vehicle import Vehicle
from app.models.waste_bin import WasteBin
