"""drop redundant sector id index

Revision ID: 77231821b4af
Revises: 4818b0de7861
Create Date: 2026-04-17 00:39:42.920441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77231821b4af'
down_revision: Union[str, Sequence[str], None] = '4818b0de7861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sector_id'), table_name='sector')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sector_id'), 'sector', ['id'], unique=False)
    # ### end Alembic commands ###
